services:
  - type: web
    name: zyslet-server
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: API_URL
        value: https://server.zyslet.com
      - key: CLIENT_URL
        value: https://zyslet.com
      - key: ADMIN_URL
        value: https://admin.zyslet.com
      - key: LOCAL_FILE_URL
        value: https://server.zyslet.com/
      - key: DATABASE_URL
        sync: false
      - key: BCRYPT_SALT_ROUNDS
        value: 10
      - key: JWT_SECRET_TOKEN
        sync: false
      - key: JWT_EXPIRE_IN
        value: 2d
      - key: JWT_REFRESH_TOKEN
        sync: false
      - key: JWT_REFRESH_EXPIRE_IN
        value: 30d
      - key: CLOUDINARY_CLOUD_NAME
        value: zyslet
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PIXEL_ID
        sync: false
